[package]
name = "ai"
version = "1.0.15"
edition = "2021"
license = "MIT"
authors = ["Still Swamp <still@itserv.ru>"]
description = "CLI utility for embedding AI into bash pipelines"
repository = "https://github.com/johnthesmith/ai-cli"

[dependencies]
#core = { path = "../../lib/core" }
core = { git = "https://github.com/johnthesmith/rust-lib-core.git", branch = "main" }
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "socks", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
regex = "1.10"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
